spring:
  h2:
    console:
      enabled: true
      
zuul:
  addProxyHeaders: false
  ignoreSecurityHeaders: false
  sensitiveHeaders:
  routes:
    first-api:
      path: /api/**
      url: http://localhost:8000/
      stripPrefix: false
    hello-world-api:
      path: /poc/**
      url: http://localhost:8083/
      stripPrefix: false      